version: '2.1'

services:

  server:
    restart: on-failure
    command: ["/app", "server"]
    build:
      context: .
    ports:
      - 80:80
    env_file:
      - .env
    healthcheck:
      test: curl --fail -s http://localhost/readiness || exit 1
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      - firestore

  migration:
    image: golang:1.13.4
    working_dir: /go/src/github.com/metabs/server
    volumes:
      - ./:/go/src/github.com/metabs/server
    env_file:
      - .env
    entrypoint: "go run cmd/migration/main.go"

  firestore:
    image: mtlynch/firestore-emulator
    env_file:
      - .env
    environment:
      - PORT=8090
    ports:
      - 8090:8090