version: '2.1'

services:

  server:
    restart: on-failure
    command: ["/app", "server"]
    build:
      context: .
    ports:
      - 80:80
    env_file:
      - .env

  firestore:
    image: mtlynch/firestore-emulator
    env_file:
      - .env
    environment:
      - PORT=8090
    ports:
      - 8090:8090