name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Prepare env files
        run: |
          cp .env.local.dist .env.local
          cp .env.dist .env
      - name: Write service account
        run: echo ${{ secrets.SERVICE_ACCOUNT_NO }} > service-account.json
      - name: Run tests
        run: env $(cat .env.local | xargs) make tests